"""Stock Indexing

Revision ID: 0a50ae5bbe9a
Revises: fe19e381f82c
Create Date: 2025-12-29 01:16:08.969389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a50ae5bbe9a'
down_revision: Union[str, Sequence[str], None] = 'fe19e381f82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grc_cgcel', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('grc_cgpisl', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grc_cgpisl', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('grc_cgcel', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
