"""Initial Migration

Revision ID: 0a87a7ae0594
Revises: 9cec9626ce4a
Create Date: 2025-12-31 17:47:03.456159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a87a7ae0594'
down_revision: Union[str, Sequence[str], None] = '9cec9626ce4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grc_cgcel', 'due_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grc_cgcel', sa.Column('due_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
