"""Spare Description

Revision ID: 0d889445096b
Revises: 70aada97bc2a
Create Date: 2026-01-13 08:17:34.994751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d889445096b'
down_revision: Union[str, Sequence[str], None] = '70aada97bc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('spare_code', sa.VARCHAR(length=30), nullable=True))
    op.add_column('complaints', sa.Column('spare_description', sa.VARCHAR(length=40), nullable=True))
    op.drop_column('complaints', 'spare')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('spare', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('complaints', 'spare_description')
    op.drop_column('complaints', 'spare_code')
    # ### end Alembic commands ###
