"""Complaints

Revision ID: 1eb25724fbac
Revises: 523b9e40026a
Create Date: 2026-01-09 22:11:33.352189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eb25724fbac'
down_revision: Union[str, Sequence[str], None] = '523b9e40026a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'customer_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('complaints', 'customer_address1',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('complaints', 'customer_city',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('complaints', 'customer_pincode',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('complaints', 'customer_contact1',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('complaints', 'updated_time',
               existing_type=postgresql.TIME(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.drop_column('complaints', 'customer_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('customer_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.alter_column('complaints', 'updated_time',
               existing_type=sa.VARCHAR(length=7),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('complaints', 'customer_contact1',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('complaints', 'customer_pincode',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('complaints', 'customer_city',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('complaints', 'customer_address1',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('complaints', 'customer_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
