"""GRC CGPISL

Revision ID: 2529614a37de
Revises: 2545a09eb5a2
Create Date: 2026-01-04 16:43:14.893585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2529614a37de'
down_revision: Union[str, Sequence[str], None] = '2545a09eb5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grc_cgpisl', sa.Column('receive_date', sa.DATE(), nullable=True))
    op.alter_column('grc_cgpisl', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=1),
               nullable=False)
    op.drop_column('grc_cgpisl', 'due_qty')
    op.drop_column('grc_cgpisl', 'remark')
    op.drop_column('grc_cgpisl', 'alt_spare_description')
    op.drop_column('grc_cgpisl_dispute', 'alt_spare_description')
    op.add_column('grc_cgpisl_return_history', sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False))
    op.add_column('grc_cgpisl_return_history', sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True))
    op.drop_column('grc_cgpisl_return_history', 'remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grc_cgpisl_return_history', sa.Column('remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('grc_cgpisl_return_history', 'dispute_remark')
    op.drop_column('grc_cgpisl_return_history', 'id')
    op.add_column('grc_cgpisl_dispute', sa.Column('alt_spare_description', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('grc_cgpisl', sa.Column('alt_spare_description', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('grc_cgpisl', sa.Column('remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('grc_cgpisl', sa.Column('due_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('grc_cgpisl', 'status',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('grc_cgpisl', 'receive_date')
    # ### end Alembic commands ###
