"""Complaint

Revision ID: 2545a09eb5a2
Revises: e1bc8da5362c
Create Date: 2026-01-03 08:51:49.702883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2545a09eb5a2'
down_revision: Union[str, Sequence[str], None] = 'e1bc8da5362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('complaint_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('complaint_head', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complaint_date', sa.DATE(), nullable=False),
    sa.Column('complaint_time', postgresql.TIME(), nullable=False),
    sa.Column('complaint_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complaint_status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('complaint_priority', sa.VARCHAR(length=15), nullable=False),
    sa.Column('action_head', sa.VARCHAR(length=30), nullable=False),
    sa.Column('action_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('technician', sa.VARCHAR(length=30), nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dealer_code', sa.VARCHAR(length=5), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('customer_address1', sa.VARCHAR(length=40), nullable=True),
    sa.Column('customer_address2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('customer_city', sa.VARCHAR(length=30), nullable=True),
    sa.Column('customer_pincode', sa.INTEGER(), nullable=True),
    sa.Column('customer_contact1', sa.BIGINT(), nullable=True),
    sa.Column('customer_contact2', sa.BIGINT(), nullable=True),
    sa.Column('product_division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('product_serial_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('product_model', sa.VARCHAR(length=25), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=25), nullable=True),
    sa.Column('purchased_from', sa.VARCHAR(length=40), nullable=True),
    sa.Column('distributor_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('spare_pending', sa.CHAR(length=1), nullable=False),
    sa.Column('spare1', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty1', sa.INTEGER(), nullable=True),
    sa.Column('indent_date1', sa.DATE(), nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty2', sa.INTEGER(), nullable=True),
    sa.Column('indent_date2', sa.DATE(), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty3', sa.INTEGER(), nullable=True),
    sa.Column('indent_date3', sa.DATE(), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty4', sa.INTEGER(), nullable=True),
    sa.Column('indent_date4', sa.DATE(), nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty5', sa.INTEGER(), nullable=True),
    sa.Column('indent_date5', sa.DATE(), nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty6', sa.INTEGER(), nullable=True),
    sa.Column('indent_date6', sa.DATE(), nullable=True),
    sa.Column('current_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rfr_number', sa.VARCHAR(length=9), nullable=True),
    sa.Column('rfr_date', sa.DATE(), nullable=True),
    sa.Column('replacement_reason', sa.VARCHAR(length=30), nullable=True),
    sa.Column('replacement_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('indent_so_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('indent_so_date', sa.DATE(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('updated_time', postgresql.TIME(), nullable=True),
    sa.Column('payment_collected', sa.CHAR(length=1), nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('payment_details', sa.VARCHAR(length=40), nullable=True),
    sa.Column('amount_sc', sa.FLOAT(), nullable=True),
    sa.Column('amount_spare', sa.FLOAT(), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['employees.name'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['technician'], ['employees.name'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('complaint_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    # ### end Alembic commands ###
