"""Parameter

Revision ID: 26f76b6c730a
Revises: 314b95e1acce
Create Date: 2026-01-26 20:44:47.547667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26f76b6c730a'
down_revision: Union[str, Sequence[str], None] = '314b95e1acce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter_last', sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False))
    op.add_column('parameter_last', sa.Column('financial_year', sa.VARCHAR(length=4), nullable=False))
    op.add_column('parameter_last', sa.Column('invoice_date_smart', sa.DATE(), nullable=False))
    op.add_column('parameter_last', sa.Column('invoice_date_unique', sa.DATE(), nullable=False))
    op.add_column('parameter_last', sa.Column('invoice_no_smart', sa.VARCHAR(length=5), nullable=False))
    op.add_column('parameter_last', sa.Column('invoice_no_unique', sa.VARCHAR(length=5), nullable=False))
    op.add_column('parameter_last', sa.Column('invoicing_permission', sa.VARCHAR(length=1), nullable=False))
    op.add_column('parameter_last', sa.Column('rfr_number', sa.VARCHAR(length=10), nullable=False))
    op.drop_column('parameter_last', 'value')
    op.drop_column('parameter_last', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter_last', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('parameter_last', sa.Column('value', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('parameter_last', 'rfr_number')
    op.drop_column('parameter_last', 'invoicing_permission')
    op.drop_column('parameter_last', 'invoice_no_unique')
    op.drop_column('parameter_last', 'invoice_no_smart')
    op.drop_column('parameter_last', 'invoice_date_unique')
    op.drop_column('parameter_last', 'invoice_date_smart')
    op.drop_column('parameter_last', 'financial_year')
    op.drop_column('parameter_last', 'id')
    # ### end Alembic commands ###
