"""Complaints

Revision ID: 29e3bab3ff61
Revises: 1eb25724fbac
Create Date: 2026-01-09 23:00:24.918252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29e3bab3ff61'
down_revision: Union[str, Sequence[str], None] = '1eb25724fbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=30), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('address2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=6), nullable=False),
    sa.Column('contact1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('contact2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('gst', sa.VARCHAR(length=15), nullable=True),
    sa.Column('consignee_address1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('consignee_address2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('consignee_city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('consignee_pin', sa.VARCHAR(length=6), nullable=False),
    sa.Column('discount_fan', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgfan', sa.FLOAT(), nullable=True),
    sa.Column('discount_sda', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgsda', sa.FLOAT(), nullable=True),
    sa.Column('discount_lt', sa.FLOAT(), nullable=True),
    sa.Column('discount_fhp', sa.FLOAT(), nullable=True),
    sa.Column('discount_pump', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgpump', sa.FLOAT(), nullable=True),
    sa.Column('discount_light', sa.FLOAT(), nullable=True),
    sa.Column('discount_whc', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgwhc', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
