"""Parameter

Revision ID: 314b95e1acce
Revises: 531111a5a052
Create Date: 2026-01-23 19:10:49.898800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '314b95e1acce'
down_revision: Union[str, Sequence[str], None] = '531111a5a052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_last',
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('value', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_last')
    # ### end Alembic commands ###
