"""Complaints

Revision ID: 3a1000e6cc91
Revises: 075fdcbb417b
Create Date: 2026-01-04 21:51:49.036985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a1000e6cc91'
down_revision: Union[str, Sequence[str], None] = '075fdcbb417b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('appoint_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'appoint_date')
    # ### end Alembic commands ###
