"""Initial Migration

Revision ID: 3cd0a852e33d
Revises: 108dbb986d1a
Create Date: 2025-12-22 22:30:49.826049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cd0a852e33d'
down_revision: Union[str, Sequence[str], None] = '108dbb986d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_cgcel',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=True),
    sa.Column('msl_qty', sa.INTEGER(), nullable=True),
    sa.Column('indent_qty', sa.INTEGER(), nullable=True),
    sa.Column('alp', sa.FLOAT(), nullable=True),
    sa.Column('purchase_price', sa.FLOAT(), nullable=True),
    sa.Column('sale_price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.drop_table('spare_cgcl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_cgcl',
    sa.Column('spare_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('msl_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('spare_code', name=op.f('spare_cgcl_pkey'))
    )
    op.drop_table('spare_cgcel')
    # ### end Alembic commands ###
