"""GRC CGPISL

Revision ID: 4458c92df7ab
Revises: 2529614a37de
Create Date: 2026-01-04 18:26:36.271806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4458c92df7ab'
down_revision: Union[str, Sequence[str], None] = '2529614a37de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cgcel', sa.Column('hsn_code', sa.VARCHAR(length=8), nullable=False))
    op.add_column('stock_cgpisl', sa.Column('hsn_code', sa.VARCHAR(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_cgpisl', 'hsn_code')
    op.drop_column('stock_cgcel', 'hsn_code')
    # ### end Alembic commands ###
