"""Stock CGPISL

Revision ID: 522e19581f78
Revises: ac8d51948511
Create Date: 2025-12-31 22:39:57.860255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '522e19581f78'
down_revision: Union[str, Sequence[str], None] = 'ac8d51948511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_cgpisl_movement',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('own_qty', sa.INTEGER(), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=False),
    sa.Column('entry_date', sa.DATE(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('complaints')
    op.drop_column('stock_cgpisl', 'discount')
    op.drop_column('stock_cgpisl', 'purchase_price')
    op.drop_column('stock_cgpisl', 'gst_rate')
    op.drop_column('stock_cgpisl', 'gst_price')
    op.drop_column('stock_cgpisl', 'msl_qty')
    op.drop_column('stock_cgpisl', 'sale_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cgpisl', sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgpisl', sa.Column('msl_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_cgpisl', sa.Column('gst_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgpisl', sa.Column('gst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgpisl', sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgpisl', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('complaints',
    sa.Column('complaint_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('complaint_head', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('complaint_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('complaint_time', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('complaint_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('complaint_status', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('complaint_priority', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('action_head', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('action_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('technician', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('customer_add1', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('customer_add2', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('customer_city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('customer_pincode', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_contact1', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_contact2', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_division', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product_slno', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('product_model', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('dealer_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('distributor_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('spare_pending', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('spare1', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_date1', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_date2', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_date3', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_date4', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty5', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_date5', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('qty6', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indent_date6', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('current_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rfr_number', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('rfr_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('replacement_reason', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('replacement_remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('indentso_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('indentso_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('updated_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_collected', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('payment_details', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('amount_sc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_spare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['employees.name'], name=op.f('complaints_action_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('complaints_created_by_fkey')),
    sa.ForeignKeyConstraint(['technician'], ['employees.name'], name=op.f('complaints_technician_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], name=op.f('complaints_updated_by_fkey')),
    sa.PrimaryKeyConstraint('complaint_number', name=op.f('complaints_pkey'))
    )
    op.drop_table('stock_cgpisl_movement')
    # ### end Alembic commands ###
