"""Sale Price

Revision ID: 531111a5a052
Revises: 0d889445096b
Create Date: 2026-01-16 09:28:20.517618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '531111a5a052'
down_revision: Union[str, Sequence[str], None] = '0d889445096b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cgcel', sa.Column('sale_price', sa.FLOAT(), nullable=True))
    op.add_column('stock_cgpisl', sa.Column('sale_price', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_cgpisl', 'sale_price')
    op.drop_column('stock_cgcel', 'sale_price')
    # ### end Alembic commands ###
