"""Initial Migration

Revision ID: 5f81d4bf4a58
Revises: 
Create Date: 2026-01-11 17:44:20.839590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f81d4bf4a58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('action_head', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('action_head')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('aadhar', sa.VARCHAR(length=12), nullable=True),
    sa.Column('pan', sa.VARCHAR(length=10), nullable=True),
    sa.Column('uan', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pf_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('joining_date', sa.DATE(), nullable=False),
    sa.Column('leaving_date', sa.DATE(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grc_cgcel_dispute',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('spare_code', 'grc_number')
    )
    op.create_table('grc_cgpisl_dispute',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('spare_code', 'grc_number')
    )
    op.create_table('holidays',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('holiday_date', sa.DATE(), nullable=False),
    sa.Column('is_holiday', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cgcel',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('cnf_qty', sa.INTEGER(), nullable=True),
    sa.Column('grc_qty', sa.INTEGER(), nullable=True),
    sa.Column('own_qty', sa.INTEGER(), nullable=True),
    sa.Column('alp', sa.FLOAT(), nullable=True),
    sa.Column('indent_qty', sa.INTEGER(), nullable=True),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_index(op.f('ix_stock_cgcel_cnf_qty'), 'stock_cgcel', ['cnf_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_grc_qty'), 'stock_cgcel', ['grc_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_indent_qty'), 'stock_cgcel', ['indent_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_own_qty'), 'stock_cgcel', ['own_qty'], unique=False)
    op.create_table('stock_cgpisl',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('cnf_qty', sa.INTEGER(), nullable=True),
    sa.Column('grc_qty', sa.INTEGER(), nullable=True),
    sa.Column('own_qty', sa.INTEGER(), nullable=True),
    sa.Column('alp', sa.FLOAT(), nullable=True),
    sa.Column('indent_qty', sa.INTEGER(), nullable=True),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_index(op.f('ix_stock_cgpisl_cnf_qty'), 'stock_cgpisl', ['cnf_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_grc_qty'), 'stock_cgpisl', ['grc_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_indent_qty'), 'stock_cgpisl', ['indent_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_own_qty'), 'stock_cgpisl', ['own_qty'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('assigned_to', sa.VARCHAR(length=30), nullable=False),
    sa.Column('resolved', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['employees.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('complaints',
    sa.Column('complaint_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('complaint_head', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complaint_date', sa.DATE(), nullable=False),
    sa.Column('complaint_time', postgresql.TIME(), nullable=False),
    sa.Column('complaint_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complaint_status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('complaint_priority', sa.VARCHAR(length=15), nullable=False),
    sa.Column('action_head', sa.VARCHAR(length=40), nullable=False),
    sa.Column('action_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('technician', sa.VARCHAR(length=30), nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('customer_address1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('customer_address2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('customer_city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('customer_pincode', sa.VARCHAR(length=6), nullable=False),
    sa.Column('customer_contact1', sa.VARCHAR(length=10), nullable=False),
    sa.Column('customer_contact2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('product_division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('product_serial_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('product_model', sa.VARCHAR(length=25), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=25), nullable=True),
    sa.Column('purchased_from', sa.VARCHAR(length=40), nullable=True),
    sa.Column('distributor_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('spare_pending', sa.CHAR(length=1), nullable=False),
    sa.Column('spare', sa.VARCHAR(length=30), nullable=True),
    sa.Column('indent_date', sa.DATE(), nullable=True),
    sa.Column('current_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rfr_number', sa.VARCHAR(length=9), nullable=True),
    sa.Column('rfr_date', sa.DATE(), nullable=True),
    sa.Column('replacement_reason', sa.VARCHAR(length=30), nullable=True),
    sa.Column('replacement_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('indent_so_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('indent_so_date', sa.DATE(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('updated_time', sa.VARCHAR(length=7), nullable=True),
    sa.Column('payment_collected', sa.CHAR(length=1), nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('payment_details', sa.VARCHAR(length=40), nullable=True),
    sa.Column('amount_sc', sa.FLOAT(), nullable=True),
    sa.Column('amount_spare', sa.FLOAT(), nullable=True),
    sa.Column('appoint_date', sa.DATE(), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['employees.name'], ),
    sa.ForeignKeyConstraint(['action_head'], ['action.action_head'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['technician'], ['employees.name'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('complaint_number')
    )
    op.create_table('customer',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=30), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('address2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=6), nullable=False),
    sa.Column('contact1', sa.VARCHAR(length=10), nullable=True),
    sa.Column('contact2', sa.VARCHAR(length=10), nullable=True),
    sa.Column('gst', sa.VARCHAR(length=15), nullable=True),
    sa.Column('consignee_address1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('consignee_address2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('consignee_city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('consignee_pin', sa.VARCHAR(length=6), nullable=False),
    sa.Column('discount_fan', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgfan', sa.FLOAT(), nullable=True),
    sa.Column('discount_sda', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgsda', sa.FLOAT(), nullable=True),
    sa.Column('discount_cglt', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgfhp', sa.FLOAT(), nullable=True),
    sa.Column('discount_pump', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgpump', sa.FLOAT(), nullable=True),
    sa.Column('discount_light', sa.FLOAT(), nullable=True),
    sa.Column('discount_whc', sa.FLOAT(), nullable=True),
    sa.Column('discount_cgwhc', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=False)
    op.create_table('grc_cgcel',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('receive_qty', sa.INTEGER(), nullable=True),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returned_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_pending_qty', sa.INTEGER(), nullable=True),
    sa.Column('receive_date', sa.DATE(), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoice', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code', 'grc_number')
    )
    op.create_table('grc_cgcel_return_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grc_cgpisl',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('receive_qty', sa.INTEGER(), nullable=True),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returned_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_pending_qty', sa.INTEGER(), nullable=True),
    sa.Column('receive_date', sa.DATE(), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoice', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code', 'grc_number')
    )
    op.create_table('grc_cgpisl_return_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cgcel_indent',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('indent_qty', sa.INTEGER(), nullable=False),
    sa.Column('indent_date', sa.DATE(), nullable=False),
    sa.Column('indent_number', sa.VARCHAR(length=6), nullable=False),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cgcel_movement',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('own_qty', sa.INTEGER(), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=False),
    sa.Column('entry_date', sa.DATE(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cgpisl_indent',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('indent_qty', sa.INTEGER(), nullable=False),
    sa.Column('indent_date', sa.DATE(), nullable=False),
    sa.Column('indent_number', sa.VARCHAR(length=6), nullable=False),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_cgpisl_indent')
    op.drop_table('stock_cgcel_movement')
    op.drop_table('stock_cgcel_indent')
    op.drop_table('grc_cgpisl_return_history')
    op.drop_table('grc_cgpisl')
    op.drop_table('grc_cgcel_return_history')
    op.drop_table('grc_cgcel')
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('complaints')
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_stock_cgpisl_own_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_indent_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_grc_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_cnf_qty'), table_name='stock_cgpisl')
    op.drop_table('stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgcel_own_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_indent_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_grc_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_cnf_qty'), table_name='stock_cgcel')
    op.drop_table('stock_cgcel')
    op.drop_table('holidays')
    op.drop_table('grc_cgpisl_dispute')
    op.drop_table('grc_cgcel_dispute')
    op.drop_table('employees')
    op.drop_table('action')
    # ### end Alembic commands ###
