"""Parameter

Revision ID: 78e280e2349d
Revises: b103204f8885
Create Date: 2026-01-26 21:51:13.417687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78e280e2349d'
down_revision: Union[str, Sequence[str], None] = 'b103204f8885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parameter_last', 'financial_year',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('parameter_last', 'invoice_date_smart',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('parameter_last', 'invoice_date_unique',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('parameter_last', 'invoice_no_smart',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('parameter_last', 'invoice_no_unique',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('parameter_last', 'invoicing_permission',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('parameter_last', 'rfr_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parameter_last', 'rfr_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('parameter_last', 'invoicing_permission',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('parameter_last', 'invoice_no_unique',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('parameter_last', 'invoice_no_smart',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('parameter_last', 'invoice_date_unique',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('parameter_last', 'invoice_date_smart',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('parameter_last', 'financial_year',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###
