"""GRC CGPISL

Revision ID: 8cf80ab6e12b
Revises: 4458c92df7ab
Create Date: 2026-01-04 19:10:48.744175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cf80ab6e12b'
down_revision: Union[str, Sequence[str], None] = '4458c92df7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('action_head', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('action_head')
    )
    op.alter_column('complaints', 'action_head',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.create_foreign_key(None, 'complaints', 'action', ['action_head'], ['action_head'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.alter_column('complaints', 'action_head',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_table('action')
    # ### end Alembic commands ###
