"""Complaints

Revision ID: 90ea39a2a09d
Revises: 3a1000e6cc91
Create Date: 2026-01-04 22:12:18.755664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90ea39a2a09d'
down_revision: Union[str, Sequence[str], None] = '3a1000e6cc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    op.drop_table('complaints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('complaint_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('complaint_head', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('complaint_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('complaint_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('complaint_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('complaint_status', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('complaint_priority', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('action_head', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('action_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('technician', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('customer_address1', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('customer_address2', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('customer_city', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('customer_pincode', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('customer_contact1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('customer_contact2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('product_division', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product_serial_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('product_model', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('purchased_from', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('distributor_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('spare_pending', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('spare', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('indent_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('current_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rfr_number', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('rfr_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('replacement_reason', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('replacement_remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('indent_so_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('indent_so_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('payment_collected', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('payment_details', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('amount_sc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_spare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('appoint_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['employees.name'], name=op.f('complaints_action_by_fkey')),
    sa.ForeignKeyConstraint(['action_head'], ['action.action_head'], name=op.f('complaints_action_head_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], name=op.f('complaints_created_by_fkey')),
    sa.ForeignKeyConstraint(['technician'], ['employees.name'], name=op.f('complaints_technician_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], name=op.f('complaints_updated_by_fkey')),
    sa.PrimaryKeyConstraint('complaint_number', name=op.f('complaints_pkey'))
    )
    op.create_table('action',
    sa.Column('action_head', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('action_head', name=op.f('action_pkey'))
    )
    # ### end Alembic commands ###
