"""GRC Migration

Revision ID: 92efbe24c7e9
Revises: 799ce7d98078
Create Date: 2025-12-28 21:16:47.248494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92efbe24c7e9'
down_revision: Union[str, Sequence[str], None] = '799ce7d98078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grc_cgcel_dispute',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('alt_spare_description', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('grc_cgpisl_dispute',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('alt_spare_description', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('grc_cgcel',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('receive_qty', sa.INTEGER(), nullable=True),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returned_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_pending_qty', sa.INTEGER(), nullable=True),
    sa.Column('due_qty', sa.INTEGER(), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('alt_spare_description', sa.VARCHAR(length=40), nullable=True),
    sa.Column('invoice', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('grc_cgcel_return_history',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('grc_cgpisl',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('receive_qty', sa.INTEGER(), nullable=True),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returned_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_pending_qty', sa.INTEGER(), nullable=True),
    sa.Column('due_qty', sa.INTEGER(), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('alt_spare_description', sa.VARCHAR(length=40), nullable=True),
    sa.Column('invoice', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('grc_cgpisl_return_history',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grc_cgpisl_return_history')
    op.drop_table('grc_cgpisl')
    op.drop_table('grc_cgcel_return_history')
    op.drop_table('grc_cgcel')
    op.drop_table('grc_cgpisl_dispute')
    op.drop_table('grc_cgcel_dispute')
    # ### end Alembic commands ###
