"""Initial Migration

Revision ID: 9cec9626ce4a
Revises: b6fb2fcf16ae
Create Date: 2025-12-31 17:13:46.198875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cec9626ce4a'
down_revision: Union[str, Sequence[str], None] = 'b6fb2fcf16ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grc_cgcel_dispute',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('spare_code', 'grc_number')
    )
    op.create_table('grc_cgpisl_dispute',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('alt_spare_description', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('stock_cgcel',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('cnf_qty', sa.INTEGER(), nullable=True),
    sa.Column('grc_qty', sa.INTEGER(), nullable=True),
    sa.Column('own_qty', sa.INTEGER(), nullable=True),
    sa.Column('alp', sa.FLOAT(), nullable=True),
    sa.Column('purchase_price', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('sale_price', sa.FLOAT(), nullable=True),
    sa.Column('gst_price', sa.FLOAT(), nullable=True),
    sa.Column('gst_rate', sa.FLOAT(), nullable=True),
    sa.Column('msl_qty', sa.INTEGER(), nullable=True),
    sa.Column('indent_qty', sa.INTEGER(), nullable=True),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_index(op.f('ix_stock_cgcel_cnf_qty'), 'stock_cgcel', ['cnf_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_grc_qty'), 'stock_cgcel', ['grc_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_indent_qty'), 'stock_cgcel', ['indent_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_own_qty'), 'stock_cgcel', ['own_qty'], unique=False)
    op.create_table('stock_cgpisl',
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('cnf_qty', sa.INTEGER(), nullable=True),
    sa.Column('grc_qty', sa.INTEGER(), nullable=True),
    sa.Column('own_qty', sa.INTEGER(), nullable=True),
    sa.Column('alp', sa.FLOAT(), nullable=True),
    sa.Column('purchase_price', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('sale_price', sa.FLOAT(), nullable=True),
    sa.Column('gst_price', sa.FLOAT(), nullable=True),
    sa.Column('gst_rate', sa.FLOAT(), nullable=True),
    sa.Column('msl_qty', sa.INTEGER(), nullable=True),
    sa.Column('indent_qty', sa.INTEGER(), nullable=True),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_index(op.f('ix_stock_cgpisl_cnf_qty'), 'stock_cgpisl', ['cnf_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_grc_qty'), 'stock_cgpisl', ['grc_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_indent_qty'), 'stock_cgpisl', ['indent_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_own_qty'), 'stock_cgpisl', ['own_qty'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('complaint_head', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complaint_date', sa.DATE(), nullable=False),
    sa.Column('complaint_time', sa.VARCHAR(length=7), nullable=False),
    sa.Column('complaint_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('complaint_status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('complaint_priority', sa.VARCHAR(length=15), nullable=False),
    sa.Column('action_head', sa.VARCHAR(length=30), nullable=False),
    sa.Column('action_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('technician', sa.VARCHAR(length=30), nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('customer_add1', sa.VARCHAR(length=40), nullable=False),
    sa.Column('customer_add2', sa.VARCHAR(length=40), nullable=True),
    sa.Column('customer_city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('customer_pincode', sa.INTEGER(), nullable=False),
    sa.Column('customer_contact1', sa.BIGINT(), nullable=False),
    sa.Column('customer_contact2', sa.BIGINT(), nullable=True),
    sa.Column('product_division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('product_slno', sa.VARCHAR(length=20), nullable=True),
    sa.Column('product_model', sa.VARCHAR(length=25), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=25), nullable=True),
    sa.Column('dealer_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('distributor_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('spare_pending', sa.CHAR(length=1), nullable=False),
    sa.Column('spare1', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty1', sa.INTEGER(), nullable=True),
    sa.Column('indent_date1', sa.DATE(), nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty2', sa.INTEGER(), nullable=True),
    sa.Column('indent_date2', sa.DATE(), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty3', sa.INTEGER(), nullable=True),
    sa.Column('indent_date3', sa.DATE(), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty4', sa.INTEGER(), nullable=True),
    sa.Column('indent_date4', sa.DATE(), nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty5', sa.INTEGER(), nullable=True),
    sa.Column('indent_date5', sa.DATE(), nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=30), nullable=True),
    sa.Column('qty6', sa.INTEGER(), nullable=True),
    sa.Column('indent_date6', sa.DATE(), nullable=True),
    sa.Column('current_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rfr_number', sa.VARCHAR(length=9), nullable=True),
    sa.Column('rfr_date', sa.DATE(), nullable=True),
    sa.Column('replacement_reason', sa.VARCHAR(length=30), nullable=True),
    sa.Column('replacement_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('indentso_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('indentso_date', sa.DATE(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('updated_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_collected', sa.CHAR(length=1), nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('payment_details', sa.VARCHAR(length=40), nullable=True),
    sa.Column('amount_sc', sa.FLOAT(), nullable=True),
    sa.Column('amount_spare', sa.FLOAT(), nullable=True),
    sa.Column('final_status', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['employees.name'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['technician'], ['employees.name'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('complaint_number')
    )
    op.create_table('grc_cgcel',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('receive_qty', sa.INTEGER(), nullable=True),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returned_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_pending_qty', sa.INTEGER(), nullable=True),
    sa.Column('receive_date', sa.DATE(), nullable=True),
    sa.Column('due_qty', sa.INTEGER(), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1), nullable=False),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoice', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code', 'grc_number')
    )
    op.create_table('grc_cgcel_return_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grc_cgpisl',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('receive_qty', sa.INTEGER(), nullable=True),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returned_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('actual_pending_qty', sa.INTEGER(), nullable=True),
    sa.Column('due_qty', sa.INTEGER(), nullable=True),
    sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('damaged_qty', sa.INTEGER(), nullable=True),
    sa.Column('short_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_qty', sa.INTEGER(), nullable=True),
    sa.Column('alt_spare_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('alt_spare_description', sa.VARCHAR(length=40), nullable=True),
    sa.Column('invoice', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('grc_cgpisl_return_history',
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('grc_number', sa.INTEGER(), nullable=False),
    sa.Column('grc_date', sa.DATE(), nullable=False),
    sa.Column('issue_qty', sa.INTEGER(), nullable=False),
    sa.Column('grc_pending_qty', sa.INTEGER(), nullable=False),
    sa.Column('good_qty', sa.INTEGER(), nullable=True),
    sa.Column('defective_qty', sa.INTEGER(), nullable=True),
    sa.Column('returning_qty', sa.INTEGER(), nullable=True),
    sa.Column('challan_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('docket_number', sa.VARCHAR(length=8), nullable=True),
    sa.Column('sent_through', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('challan_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['challan_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('spare_code')
    )
    op.create_table('stock_cgcel_indent',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('indent_qty', sa.INTEGER(), nullable=False),
    sa.Column('indent_date', sa.DATE(), nullable=False),
    sa.Column('indent_number', sa.VARCHAR(length=6), nullable=False),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cgcel_movement',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('own_qty', sa.INTEGER(), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=False),
    sa.Column('entry_date', sa.DATE(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cgpisl_indent',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('spare_code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('division', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spare_description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('indent_qty', sa.INTEGER(), nullable=False),
    sa.Column('indent_date', sa.DATE(), nullable=False),
    sa.Column('indent_number', sa.VARCHAR(length=6), nullable=False),
    sa.Column('party_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('remark', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_cgpisl_indent')
    op.drop_table('stock_cgcel_movement')
    op.drop_table('stock_cgcel_indent')
    op.drop_table('grc_cgpisl_return_history')
    op.drop_table('grc_cgpisl')
    op.drop_table('grc_cgcel_return_history')
    op.drop_table('grc_cgcel')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_stock_cgpisl_own_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_indent_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_grc_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_cnf_qty'), table_name='stock_cgpisl')
    op.drop_table('stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgcel_own_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_indent_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_grc_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_cnf_qty'), table_name='stock_cgcel')
    op.drop_table('stock_cgcel')
    op.drop_table('grc_cgpisl_dispute')
    op.drop_table('grc_cgcel_dispute')
    # ### end Alembic commands ###
