"""GRC Migration

Revision ID: 9fd9fbc7b02c
Revises: 92efbe24c7e9
Create Date: 2025-12-28 22:18:43.807437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fd9fbc7b02c'
down_revision: Union[str, Sequence[str], None] = '92efbe24c7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grc_cgcel', 'challan_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('grc_cgpisl', 'challan_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grc_cgpisl', 'challan_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('grc_cgcel', 'challan_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
