"""Initial Migration

Revision ID: ac8d51948511
Revises: 0a87a7ae0594
Create Date: 2025-12-31 17:51:30.972857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac8d51948511'
down_revision: Union[str, Sequence[str], None] = '0a87a7ae0594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_cgcel', 'msl_qty')
    op.drop_column('stock_cgcel', 'gst_price')
    op.drop_column('stock_cgcel', 'discount')
    op.drop_column('stock_cgcel', 'gst_rate')
    op.drop_column('stock_cgcel', 'purchase_price')
    op.drop_column('stock_cgcel', 'sale_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cgcel', sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgcel', sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgcel', sa.Column('gst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgcel', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgcel', sa.Column('gst_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_cgcel', sa.Column('msl_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
