"""Parameter

Revision ID: b103204f8885
Revises: c80a5a96d5c8
Create Date: 2026-01-26 21:10:52.511218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b103204f8885'
down_revision: Union[str, Sequence[str], None] = 'c80a5a96d5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_last',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('financial_year', sa.VARCHAR(length=4), nullable=True),
    sa.Column('invoice_date_smart', sa.DATE(), nullable=True),
    sa.Column('invoice_date_unique', sa.DATE(), nullable=True),
    sa.Column('invoice_no_smart', sa.VARCHAR(length=5), nullable=True),
    sa.Column('invoice_no_unique', sa.VARCHAR(length=5), nullable=True),
    sa.Column('invoicing_permission', sa.VARCHAR(length=1), nullable=True),
    sa.Column('rfr_number', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_last')
    # ### end Alembic commands ###
