"""Initial Migration

Revision ID: b6fb2fcf16ae
Revises: 
Create Date: 2025-12-31 16:48:18.135132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6fb2fcf16ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('aadhar', sa.VARCHAR(length=12), nullable=True),
    sa.Column('pan', sa.VARCHAR(length=10), nullable=True),
    sa.Column('uan', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pf_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('joining_date', sa.DATE(), nullable=False),
    sa.Column('leaving_date', sa.DATE(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holidays',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('holiday_date', sa.DATE(), nullable=False),
    sa.Column('is_holiday', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('assigned_to', sa.VARCHAR(length=30), nullable=False),
    sa.Column('resolved', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['employees.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_table('holidays')
    op.drop_table('employees')
    # ### end Alembic commands ###
