"""Initial Migration

Revision ID: c4d51b06e6f7
Revises: 3cd0a852e33d
Create Date: 2025-12-22 22:42:17.818457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4d51b06e6f7'
down_revision: Union[str, Sequence[str], None] = '3cd0a852e33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'aadhar',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('employees', 'pan',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('employees', 'uan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employees', 'pf_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pf_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employees', 'uan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employees', 'pan',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('employees', 'aadhar',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
