"""Parameter

Revision ID: c80a5a96d5c8
Revises: 252a2ca74759
Create Date: 2026-01-26 21:08:48.298253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c80a5a96d5c8'
down_revision: Union[str, Sequence[str], None] = '252a2ca74759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_last')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_last',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('financial_year', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('invoice_date_smart', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_date_unique', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_no_smart', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('invoice_no_unique', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('invoicing_permission', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('rfr_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
