"""Complaints

Revision ID: d2c9d2f03be8
Revises: 29e3bab3ff61
Create Date: 2026-01-10 00:06:55.840715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2c9d2f03be8'
down_revision: Union[str, Sequence[str], None] = '29e3bab3ff61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('discount_cglt', sa.FLOAT(), nullable=True))
    op.add_column('customer', sa.Column('discount_cgfhp', sa.FLOAT(), nullable=True))
    op.drop_column('customer', 'discount_fhp')
    op.drop_column('customer', 'discount_lt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('discount_lt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('discount_fhp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('customer', 'discount_cgfhp')
    op.drop_column('customer', 'discount_cglt')
    # ### end Alembic commands ###
