"""GRC CGCEL

Revision ID: e1bc8da5362c
Revises: 522e19581f78
Create Date: 2026-01-01 21:23:41.582761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1bc8da5362c'
down_revision: Union[str, Sequence[str], None] = '522e19581f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grc_cgcel', 'remark')
    op.add_column('grc_cgcel_return_history', sa.Column('dispute_remark', sa.VARCHAR(length=40), nullable=True))
    op.drop_column('grc_cgcel_return_history', 'remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grc_cgcel_return_history', sa.Column('remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('grc_cgcel_return_history', 'dispute_remark')
    op.add_column('grc_cgcel', sa.Column('remark', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
