"""Stock Indexing

Revision ID: fe19e381f82c
Revises: 9fd9fbc7b02c
Create Date: 2025-12-28 22:26:46.723246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe19e381f82c'
down_revision: Union[str, Sequence[str], None] = '9fd9fbc7b02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_cgcel_cnf_qty'), 'stock_cgcel', ['cnf_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_grc_qty'), 'stock_cgcel', ['grc_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_indent_qty'), 'stock_cgcel', ['indent_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgcel_own_qty'), 'stock_cgcel', ['own_qty'], unique=False)
    op.add_column('stock_cgpisl', sa.Column('party_name', sa.VARCHAR(length=30), nullable=True))
    op.add_column('stock_cgpisl', sa.Column('order_number', sa.VARCHAR(length=30), nullable=True))
    op.add_column('stock_cgpisl', sa.Column('order_date', sa.DATE(), nullable=True))
    op.add_column('stock_cgpisl', sa.Column('remark', sa.VARCHAR(length=40), nullable=True))
    op.create_index(op.f('ix_stock_cgpisl_cnf_qty'), 'stock_cgpisl', ['cnf_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_grc_qty'), 'stock_cgpisl', ['grc_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_indent_qty'), 'stock_cgpisl', ['indent_qty'], unique=False)
    op.create_index(op.f('ix_stock_cgpisl_own_qty'), 'stock_cgpisl', ['own_qty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_cgpisl_own_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_indent_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_grc_qty'), table_name='stock_cgpisl')
    op.drop_index(op.f('ix_stock_cgpisl_cnf_qty'), table_name='stock_cgpisl')
    op.drop_column('stock_cgpisl', 'remark')
    op.drop_column('stock_cgpisl', 'order_date')
    op.drop_column('stock_cgpisl', 'order_number')
    op.drop_column('stock_cgpisl', 'party_name')
    op.drop_index(op.f('ix_stock_cgcel_own_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_indent_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_grc_qty'), table_name='stock_cgcel')
    op.drop_index(op.f('ix_stock_cgcel_cnf_qty'), table_name='stock_cgcel')
    # ### end Alembic commands ###
